# Generated by Django 4.1 on 2023-01-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventory',
            name='available',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='available',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
