# Generated by Django 4.1 on 2023-11-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_alter_product_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventory',
            name='quantity_transfered',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity_transfered',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinventory',
            name='quantity_restocked',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity_restocked',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
