# Generated by Django 4.1 on 2023-12-08 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_historicalinventory_quantity_transfered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventory',
            name='transfer_from',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ims.product'),
        ),
        migrations.AddField(
            model_name='historicalinventory',
            name='transfer_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ims.product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='transfer_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to='ims.product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='transfer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='ims.product'),
        ),
    ]
