# Generated by Django 4.1 on 2023-01-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
